# Render service spec example. Edit to match whether you want a static site or a Node web service.

services:
  - type: web
    name: lukas-vine-web
    env: node
    repo: https://github.com/johnathanvargas/Lukas-VINE
    branch: main
    buildCommand: 'npm install'
    startCommand: 'node server/index.js'
